services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile.dev
    ports:
      - "5038:5038"
    env_file: .env
    environment:
      - DATABASE_URL=sqlite:///data/void-eid.db?mode=rwc
      - PORT=5038
    volumes:
      - ./data:/data
      - ./src/backend:/usr/src/app
      - /usr/src/app/target # Prevent overwriting container target with host target
    restart: unless-stopped

  murmur:
    build:
      context: ./src/murmur
      dockerfile: Dockerfile
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    env_file: .env
    environment:
      - BACKEND_URL=http://backend:5038/api/internal/mumble
    volumes:
      - ./data/murmur:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file: .env
    environment:
      - VITE_API_URL=http://localhost:5038
    volumes:
      - ./src/frontend:/app
      - /app/node_modules # Prevent overwriting container node_modules
    depends_on:
      - backend
    restart: unless-stopped
